baseurl = "https://ykhorzon.github.io/"


# Enable comments by entering your Disqus shortname
disqusShortname = "ykhorzon-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-97451129-2"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."

# languageCode = "en-us"
DefaultContentLanguage = "tw"
[Languages]
[Languages.en]
title = "Momentum of Ykhorizon"
weight = 2

[Languages.tw]
title = "Momentum of Ykhorizon"
weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Ykhorizon"
    bio = "Programming, Agile, Startup\nAgriculture, Sustainable, Irrigation\n Music, Blues, Guitar"
    location = "Taiwan"
    site_description = "An awesome website providing information about technology combining agriculture and music"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice). All right reserved for ykhorizon"
    avatar = "css/images/me.jpg"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    # gravatar = "ykhorizon.light@gmail.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["blog"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/custom_css.js"]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.menu]]
    before = false
    label = "Project"
    link   = "project/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/ykhorzon"
    

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "ykhorzon"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "spf13"

# Enable and disable widgets for the right sidebar
[params.widgets]
    profile = true
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
